### PR TITLE
Makefile: Add the install/uninstall hooks

### PR DESCRIPTION
**Pull request by fabioestevam**
Improve the Makefile by adding the install/uninstall hooks.

This makes it easier for packaging the project when using OpenEmbedded, for example.

Signed-off-by: Fabio Estevam <festevam@denx.de>

### CODE REVIEW

**Comment by kisvegabor** [comment]
Makes sense, thank you!

**Comment by kisvegabor** [comment]
Could you add a few lines about it in the README?

**Comment by fabioestevam** [comment]
Hi @kisvegabor 

I have added some lines in README to explain that.

Please let me know if you are OK with it.

Thanks

**Comment by kisvegabor** [comment]
Nice! Thank you!

**Pull request merged**
