### PR TITLE
build: Add Helper rule to update gitmodules

### PR DESCRIPTION
**Pull request by rzr**
Signed-off-by: Philippe Coval <philippe.coval@huawei.com>

### CODE REVIEW

**Comment by kisvegabor** [comment]
On every `make` will it automatically update submodules too? If so will make fail is there is no internet connection?

**Comment by rzr** [comment]
not if prep.tmp file is there

**Comment by kisvegabor** [comment]
I see, I've tried it out and it was working well. But I'm thinking about if there could be any unwanted unexpected consequences if the submodules are updated automatically.  E.g. someone uses lvgl v8.0.2 but v8.1 will be out it's not certain that he want to update to the new minor version automatically. 

I'd rather leave for the user to update the submodules as he wish.

**Comment by rzr** [comment]
ok let me update this change to pull only if missing

**Comment by kisvegabor** [comment]
Sounds good!

**Comment by kisvegabor** [comment]
I don't know why but the content of `lvgl.mk`, `lv_drivers.mk` or `lv_demos.mk` randomly gets overwritten by this content:
```
lv_demos/lv_demo.mk
lv_drivers/lv_drivers.mk
lvgl/lvgl.mk
```

E.g. when `lv_demos.mk` was overwritten:
```shell
$ make
info: Preparing sources
git submodule init
git submodule update
info: Sources prepared ready to build again
Makefile:50: recipe for target 'lv_demos/lv_demo.mk' failed
make: *** [lv_demos/lv_demo.mk] Error 1
```

**Comment by embeddedt** [comment]
It's been a while since I worked with a Makefile, but I think [this line](https://github.com/lvgl/lv_port_linux_frame_buffer/pull/15/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R53) is the culprit.

**Pull request closed without merging**
